version: '3.7'

services:
  shopping-client:
    build:
      context: ./client
      dockerfile: Dockerfile

    volumes:
      - './client:/app'
      - '/app/node_modules'

    ports:
      - 3000:3000

    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true
